### ISSUE TITLE
Bugs of Order Requirements

### ISSUE THREAD

**Issue by Chromowolf** [Buizz/EUD-Editor-3#48] opened 2021-06-06 05:56 UTC
The default of Order 119 (Dark Swarm) should be "Don't Use".
OP code of "Don't Use": None
OP code of "Always Use": 0xHH 0xHH 0xFF 0xFF, with the first 2 bytes being the order ID
In EE3, if I change the requirement of Order 119 from "Default" to "Always Use":
![image](https://user-images.githubusercontent.com/37732663/120914139-9c227a80-c6ce-11eb-9d83-c98a10de0688.png)

then compile, and new OP code is generated in RequireData (as expected):
![image](https://user-images.githubusercontent.com/37732663/120914154-ae9cb400-c6ce-11eb-9025-2e30038045d9.png)

However, if I then change the requirement to "Default" (which should be "Don't Use"), I still get:

![image](https://user-images.githubusercontent.com/37732663/120914175-ce33dc80-c6ce-11eb-9583-debcce6304b2.png)

After compiling, the OP code in RequireData remains to be "0x77 0x00 0xFF 0xFF" (Always Use):

![image](https://user-images.githubusercontent.com/37732663/120914194-ffaca800-c6ce-11eb-9e65-45e0b48aeb6b.png)

If I switch among the 5 choices, this strange bug remains. It seems that EE3 fails to update the required data correctly when user switches selections.

**Comment by Buizz** [comment] 2021-06-06 12:52
'77 00 FF FF' is the beginning of the use of Dark Swarm.
Without this part, compilation will fail and the header will be generated no matter what requirements are selected.

**Comment by Chromowolf** [comment] 2021-06-06 13:32
> Without this part, compilation will fail and the header will be generated no matter what requirements are selected.

I'm fraid no. The normal requirement has no "77 00 FF FF", so that it the length of Order Requirement Data is 1316 bytes.
If "77 00 FF FF" is added, the length becomes 1320 bytes, and the game will crash.

Open the original RequireData file in Hex:
![image](https://user-images.githubusercontent.com/37732663/120926201-8cc32180-c70e-11eb-9f1c-9007f54588b3.png)

Search for bytes value "77 00 FF FF":
![image](https://user-images.githubusercontent.com/37732663/120926224-9c426a80-c70e-11eb-9a75-9e9d4bc4d7cf.png)

The result is:
![Uploading image.png…]()

**Comment by Buizz** [comment] 2021-06-06 14:11
![image](https://user-images.githubusercontent.com/19189816/120927580-5391ae00-c71c-11eb-9338-1ae3b286fb7c.png)

How does the capacity change if you choose "User Custom"?

**Comment by Buizz** [comment] 2021-06-06 14:16
And here's the logic to make Req.
https://github.com/Buizz/EUD-Editor-3/blob/master/EUD%20Editor%203/Class/BulidData/WriteReqFile.vb

**Comment by Chromowolf** [comment] 2021-06-06 14:16
Original:
![image](https://user-images.githubusercontent.com/37732663/120927706-61dbcc00-c714-11eb-900b-886dba17f4b2.png)

If I choose user custom:
![image](https://user-images.githubusercontent.com/37732663/120927719-715b1500-c714-11eb-8eba-f5ff6bc52c8d.png)

This is as expected. Because any custom OP code must be added between "77 00" and "FF FF".

Now, if I compile:
![image](https://user-images.githubusercontent.com/37732663/120927787-ad8e7580-c714-11eb-986f-8e0131b28f9a.png)

After compiling is finished, I then change it to "Default", then the capacity remains to be 1320/1316, this is where the bug is (I think):
![image](https://user-images.githubusercontent.com/37732663/120927834-d57dd900-c714-11eb-87b3-40fb6078ce86.png)

Cuz we know that, "Default" = "Don't Use" = no OP code at all

**Comment by Chromowolf** [comment] 2021-06-06 14:21
In short:
Originally, "Default" is selected, capacity = 1316/1316
Step 1: I switch to "User Custom", then capacity = 1320/1316
Step 2: I switch back to "Default", then capacity = 1316/1316
The above is alright.

However, If I compile the project between step 1 and 2, then the capacity cannot go back to normal:
Originally, "Default" is selected, capacity = 1316/1316
Step 1    : switch to "User Custom", then capacity = 1320/1316
Step 1.5 : Compile
Step 2    : switch back to "Default", then capacity = 1320/1316 (bug)

**Comment by Buizz** [comment] 2021-06-07 01:08
Okay, i will check it.

**Comment by Buizz** [comment] 2021-06-24 13:02
I found the cause.
It will be fixed in 0.12.5.1 version.

**Closed** 2021-06-24 13:11 UTC
